/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyApp {
    }
    interface MyButton {
    }
    interface MyForm {
    }
    interface MyInput {
    }
    interface MyTimer {
    }
    interface TextField {
        /**
          * The text to display as an h1 element.
         */
        "text": string;
    }
}
declare global {
    interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {
    }
    var HTMLMyAppElement: {
        prototype: HTMLMyAppElement;
        new (): HTMLMyAppElement;
    };
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyFormElement extends Components.MyForm, HTMLStencilElement {
    }
    var HTMLMyFormElement: {
        prototype: HTMLMyFormElement;
        new (): HTMLMyFormElement;
    };
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    interface HTMLMyTimerElement extends Components.MyTimer, HTMLStencilElement {
    }
    var HTMLMyTimerElement: {
        prototype: HTMLMyTimerElement;
        new (): HTMLMyTimerElement;
    };
    interface HTMLTextFieldElement extends Components.TextField, HTMLStencilElement {
    }
    var HTMLTextFieldElement: {
        prototype: HTMLTextFieldElement;
        new (): HTMLTextFieldElement;
    };
    interface HTMLElementTagNameMap {
        "my-app": HTMLMyAppElement;
        "my-button": HTMLMyButtonElement;
        "my-form": HTMLMyFormElement;
        "my-input": HTMLMyInputElement;
        "my-timer": HTMLMyTimerElement;
        "text-field": HTMLTextFieldElement;
    }
}
declare namespace LocalJSX {
    interface MyApp {
    }
    interface MyButton {
    }
    interface MyForm {
    }
    interface MyInput {
    }
    interface MyTimer {
    }
    interface TextField {
        /**
          * The text to display as an h1 element.
         */
        "text"?: string;
    }
    interface IntrinsicElements {
        "my-app": MyApp;
        "my-button": MyButton;
        "my-form": MyForm;
        "my-input": MyInput;
        "my-timer": MyTimer;
        "text-field": TextField;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-app": LocalJSX.MyApp & JSXBase.HTMLAttributes<HTMLMyAppElement>;
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-form": LocalJSX.MyForm & JSXBase.HTMLAttributes<HTMLMyFormElement>;
            "my-input": LocalJSX.MyInput & JSXBase.HTMLAttributes<HTMLMyInputElement>;
            "my-timer": LocalJSX.MyTimer & JSXBase.HTMLAttributes<HTMLMyTimerElement>;
            "text-field": LocalJSX.TextField & JSXBase.HTMLAttributes<HTMLTextFieldElement>;
        }
    }
}
